### ISSUE TITLE
Showcase examples in the Cookbook

### ISSUE THREAD

**Issue by milesfrain** [artemisSystem/purescript-game#3]
We have a few game recipes in the [cookbook](https://github.com/JordanMartinez/purescript-cookbook/blob/master/README.md):

* [SignalSnakeJs](https://try.ps.ai/?github=JordanMartinez/purescript-cookbook/master/recipes/SignalSnakeJs/src/Main.purs)
* [SignalTrisJs](https://try.ps.ai/?github=JordanMartinez/purescript-cookbook/master/recipes/SignalTrisJs/src/Main.purs)
* [BehaviorSuperCircleJs](https://try.ps.ai/?github=JordanMartinez/purescript-cookbook/master/recipes/BehaviorSuperCircleJs/src/Main.purs)

Seeing one or more of those examples ported to `purescript-game` would be really illuminating for seeing how this library works.

**Comment by 3ddyy** [comment]
Great idea! I might get to this tomorrow. Is TryPurescript compatibility important? None of my packages are in the package set yet, and the rewrite of `game` isn't even released as a tag here on github yet, so getting it to work on there might be difficult.

**Comment by milesfrain** [comment]
You can create a PR where it works locally with an overridden package set, and then it will be ready to merge once the library is incorporated into the official package set. Similar to what's being done in https://github.com/JordanMartinez/purescript-cookbook/pull/226

**Comment by 3ddyy** [comment]
Okay! Thanks for info
